=== apache/ofbiz-framework/framework/base/dtd/ofbiz-properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd" />

    <xs:complexType name="valueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required" />
                <xs:attribute ref="xml:space" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="resource">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="value" type="valueType" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="key" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== apache/ofbiz-framework/applications/commonext/config/CommonExtUiLabels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://ofbiz.apache.org/dtds/ofbiz-properties.xsd">
    <property key="CommonExtCreatePublicMessage">
        <value xml:lang="de">Erzeuge öffentliche Nachricht</value>
        <value xml:lang="en">Create Public Message</value>
        <value xml:lang="fr">Créer un message public</value>
        <value xml:lang="it">Crea messaggio pubblico</value>
        <value xml:lang="ja">公開メッセージを作成</value>
        <value xml:lang="nl">Nieuw publiek bericht aanmaken</value>
        <value xml:lang="pt-BR">Criar Mensagem Pública</value>
        <value xml:lang="vi">Tạo thông điệp công khai</value>
        <value xml:lang="zh">新建公共消息</value>
        <value xml:lang="zh-TW">新建公共訊息</value>
    </property>
    <property key="CommonExtDateInfoCreated">
        <value xml:lang="de">Datum Info erzeugt</value>
        <value xml:lang="en">Date info created</value>
        <value xml:lang="fr">Date de création</value>
        <value xml:lang="it">Data di creazione</value>
        <value xml:lang="ja">作成日付情報</value>
        <value xml:lang="nl">Datum info gegenereerd</value>
        <value xml:lang="pt-BR">Data da informação criada</value>
        <value xml:lang="vi">Ngày tạo thông tin</value>
        <value xml:lang="zh">已创建日期信息</value>
        <value xml:lang="zh-TW">已新建日期資訊</value>
    </property>
    <property key="CommonExtDateLastChanged">
        <value xml:lang="de">Datum Letzte Änderung</value>
        <value xml:lang="en">Date Last Changed</value>
        <value xml:lang="fr">Dernière date de changement</value>
        <value xml:lang="it">Data ultimo cambiamento</value>
        <value xml:lang="ja">最終更新日</value>
        <value xml:lang="nl">Datum laatste verandering</value>
        <value xml:lang="pt-BR">Data da última modificação</value>
        <value xml:lang="vi">Ngày thay đổi thông tin</value>
        <value xml:lang="zh">最后修改日期</value>
        <value xml:lang="zh-TW">最後修改日期</value>
    </property>
    <property key="CommonExtSystemInfoNote">
        <value xml:lang="de">Systemnachricht</value>
        <value xml:lang="en">System Info Note</value>
        <value xml:lang="fr">Message d'information système</value>
        <value xml:lang="it">Messaggio di sistema</value>
        <value xml:lang="ja">システム情報連絡</value>
        <value xml:lang="nl">Systeembericht</value>
        <value xml:lang="pt-BR">Nota de Informação do Sistema</value>
        <value xml:lang="vi">Thông tin lưu ý mức hệ thống</value>
        <value xml:lang="zh">系统信息便笺</value>
        <value xml:lang="zh-TW">系統資訊便箋</value>
    </property>
    <property key="CommonExtSystemInfoNoteForUser">
        <value xml:lang="de">Systemnachricht für Benutzer:</value>
        <value xml:lang="en">System Info note for user:</value>
        <value xml:lang="fr">Message d'information système pour l'utilisateur :</value>
        <value xml:lang="it">Messaggio di sistema per l'utente:</value>
        <value xml:lang="ja">システム情報連絡 ユーザ:</value>
        <value xml:lang="nl">Systeembericht voor gebruiker</value>
        <value xml:lang="pt-BR">Nota de Informação do Sistema para o usuário:</value>
        <value xml:lang="vi">Thông tin lưu ý mức hệ thống tới Người dùng:</value>
        <value xml:lang="zh">系统信息便笺致用户：</value>
        <value xml:lang="zh-TW">系統資訊便箋致使用者:</value>
    </property>
    <property key="CommonExtSystemInfoStatus">
        <value xml:lang="de">System Information Status</value>
        <value xml:lang="en">System Info Status</value>
        <value xml:lang="fr">Message d'information d'état</value>
        <value xml:lang="it">Stato messaggi di sistema</value>
        <value xml:lang="ja">システム情報ステータス</value>
        <value xml:lang="nl">Systeem info status</value>
        <value xml:lang="pt-BR">Informação de estado do sistema</value>
        <value xml:lang="vi">Trạng thái mức hệ thống</value>
        <value xml:lang="zh">系统信息状态</value>
        <value xml:lang="zh-TW">系統資訊狀態</value>
    </property>
    <property key="CommonExtSystemInfoStatusForUser">
        <value xml:lang="de">System Information Status für Benutzer:</value>
        <value xml:lang="en">System Info status for user:</value>
        <value xml:lang="fr">Message d'information d'état pour l'utilisateur :</value>
        <value xml:lang="it">Stato messaggi di sistema per l'utente:</value>
        <value xml:lang="ja">システム情報ステータス ユーザ:</value>
        <value xml:lang="nl">Systeem info status voor gebruiker</value>
        <value xml:lang="pt-BR">Informação de estado do sistema para o usuário:</value>
        <value xml:lang="vi">Trạng thái mức hệ thống tới Người dùng:</value>
        <value xml:lang="zh">系统信息状态为用户：</value>
        <value xml:lang="zh-TW">系統資訊狀態為使用者:</value>
    </property>
</resource>

=== apache/ofbiz-framework/framework/minilang/config/DefaultMessagesUiLabels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
-->
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://ofbiz.apache.org/dtds/ofbiz-properties.xsd">
    <property key="check.error.prefix">
        <value xml:lang="de">Fehler: </value>
        <value xml:lang="en">Error: </value>
        <value xml:lang="fr">Erreur : </value>
        <value xml:lang="it">Errore: </value>
        <value xml:lang="ja">エラー:</value>
        <value xml:lang="nl">Fout: </value>
        <value xml:lang="zh">错误：</value>
        <value xml:lang="zh-TW">錯誤:</value>
    </property>
    <property key="check.error.suffix">
        <value xml:lang="en"> </value>
    </property>
    <property key="check.message.prefix">
        <value xml:lang="en"> </value>
    </property>
    <property key="check.message.suffix">
        <value xml:lang="en"> </value>
    </property>
    <property key="service.default.message">
        <value xml:lang="de">Aktion erfolgreich ausgeführt.</value>
        <value xml:lang="en">The action was performed successfully.</value>
        <value xml:lang="es">Se ha realizado la acción correctamente</value>
        <value xml:lang="fr">Opération réussie.</value>
        <value xml:lang="it">L'azione è stata eseguita con successo.</value>
        <value xml:lang="ja">操作は成功しました。</value>
        <value xml:lang="nl">De acties is met succes uitgevoerd.</value>
        <value xml:lang="ro">Operatia a fost executata cu succes.</value>
        <value xml:lang="ru">Действие выполнено успешно.</value>
        <value xml:lang="th">การปฏิบัติหน้าที่เสร็จสมบูรณ์แล้ว</value>
        <value xml:lang="zh">已成功执行本操作。</value>
        <value xml:lang="zh-TW">已成功執行本操作.</value>
    </property>
    <property key="service.error.prefix">
        <value xml:lang="de">Fehler: </value>
        <value xml:lang="en">Error: </value>
        <value xml:lang="fr">Erreur : </value>
        <value xml:lang="it">Errore: </value>
        <value xml:lang="ja">エラー:</value>
        <value xml:lang="nl">Fout: </value>
        <value xml:lang="zh">错误：</value>
        <value xml:lang="zh-TW">錯誤:</value>
    </property>
    <property key="service.error.suffix">
        <value xml:lang="en"> </value>
    </property>
    <property key="service.message.prefix">
        <value xml:lang="en"> </value>
    </property>
    <property key="service.message.suffix">
        <value xml:lang="en"> </value>
    </property>
    <property key="service.success.prefix">
        <value xml:lang="en"> </value>
    </property>
    <property key="service.success.suffix">
        <value xml:lang="en"> </value>
    </property>
</resource>
