=== apache/ofbiz-framework/framework/base/dtd/ofbiz-containers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="ofbiz-containers">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="container"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="container">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.container"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.container">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="class" use="required"/>
    </xs:attributeGroup>
    <xs:element name="property">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
                <xs:element minOccurs="0" ref="property-value"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.property"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.property">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value"/>
    </xs:attributeGroup>
    <xs:element name="property-value" type="any"/>
    <xs:complexType name="any" mixed="true">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
<!--
    
    Container properties are relative to the implementation class for details
    of which properties are available see the docs on the class defined.
    
    Example:
    
    <ofbiz-containers>
        <container name="jetty-container" class="org.ofbiz.base.container.JettyContainer">
            <property name="default-listener">
              <property name="type" value="default"/>
              <property name="host" value="0.0.0.0"/>
              <property name="port" value="8080"/>
              <property name="min-threads" value="5"/>
              <property name="max-threads" value="250"/>
              <property name="max-idle-time" value="30000"/>
              <property name="max-read-time" value="60000"/>
            </property>
        </container>
        <container name="component-container" class="org.ofbiz.base.container.ComponentContainer">
            <property name="entity" value="${ofbiz.home}/framework/entity/component.xml"/>
            <property name="service" value="${ofbiz.home}/framework/service/component.xml"/>
            <property name="party" value="${ofbiz.home}/applications/party/component.xml"/>
        </container>
    </ofbiz-containers>
    
-->

=== apache/ofbiz-framework/framework/base/config/rmi-containers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
-->

<ofbiz-containers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://ofbiz.apache.org/dtds/ofbiz-containers.xsd">
    <!-- load the ofbiz component container (always first) -->
    <container name="component-container" class="org.ofbiz.base.container.ComponentContainer"/>

    <!-- load the cached classloader container (always second) -->
    <container name="classloader-container" class="org.ofbiz.base.container.ClassLoaderContainer"/>

    <!-- load the naming (JNDI) server -->
    <container name="naming-container" class="org.ofbiz.base.container.NamingServiceContainer">
        <property name="port" value="1099"/>
    </container>

    <!-- RMI Service Dispatcher -->
    <container name="rmi-dispatcher" class="org.ofbiz.service.rmi.RmiServiceContainer">
        <property name="bound-name" value="RMIDispatcher"/>
        <property name="bound-host" value="127.0.0.1"/>
        <property name="bound-port" value="1099"/>
        <property name="delegator-name" value="default"/>
        <property name="client-factory" value="org.ofbiz.service.rmi.socket.ssl.SSLClientSocketFactory"/>
        <property name="server-factory" value="org.ofbiz.service.rmi.socket.ssl.SSLServerSocketFactory"/>
        <property name="ssl-keystore" value="framework/base/config/ofbizrmi.jks"/>
        <property name="ssl-keystore-type" value="JKS"/>
        <property name="ssl-keystore-pass" value="changeit"/>
        <property name="ssl-keystore-alias" value="rmissl"/>
        <property name="ssl-client-auth" value="true"/>
    </container>

</ofbiz-containers>
